version: '3.8'

services:
  # Spring Boot Application
  spring-app:
    image: petshop-backend:latest
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/petshop
    depends_on:
      - mysql
    networks:   # Define the network here
      - petshop-network

  # MySQL Database
  mysql:
    image: mysql:5.7
    container_name: petshop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: petshop
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:   # Define the network here
      - petshop-network

  # React Application
  frontend:
    image: frontend-app:latest
    container_name: petshop-frontend
    ports:
      - "3030:80"
    volumes:
      - ./:/frontend
      - /frontend/node_modules
    tty: true
    networks:   # Define the network here
      - petshop-network

networks:   # Define the custom network at the end of the file
  petshop-network:
