version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: petshop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: petshop
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
#networks:
#  default:
#    driver: bridge
